@startuml TimerStates
state "TimerStates State" as CodeJunkie_StateChart_Tutorial_TimerStates_State {
  state "PoweredOff" as CodeJunkie_StateChart_Tutorial_TimerStates_State_PoweredOff
  state "PoweredOn" as CodeJunkie_StateChart_Tutorial_TimerStates_State_PoweredOn
}

CodeJunkie_StateChart_Tutorial_TimerStates_State_PoweredOff --> CodeJunkie_StateChart_Tutorial_TimerStates_State_PoweredOn : PowerButtonPressed
CodeJunkie_StateChart_Tutorial_TimerStates_State_PoweredOn --> CodeJunkie_StateChart_Tutorial_TimerStates_State_PoweredOff : PowerButtonPressed

CodeJunkie_StateChart_Tutorial_TimerStates_State_PoweredOff : OnEnter → PoweredOff
CodeJunkie_StateChart_Tutorial_TimerStates_State_PoweredOn : OnEnter → PoweredOn

[*] --> CodeJunkie_StateChart_Tutorial_TimerStates_State_PoweredOff
@enduml