```mermaid
stateDiagram-v2
    state "Timer State" as CodeJunkie_StateChart_Example_Timer_State {
        state "PoweredOff" as CodeJunkie_StateChart_Example_Timer_State_PoweredOff
        state "PoweredOn" as CodeJunkie_StateChart_Example_Timer_State_PoweredOn
    }
    [*] --> CodeJunkie_StateChart_Example_Timer_State_PoweredOff
    CodeJunkie_StateChart_Example_Timer_State_PoweredOff --> CodeJunkie_StateChart_Example_Timer_State_PoweredOn : PowerButtonPressed
    CodeJunkie_StateChart_Example_Timer_State_PoweredOn --> CodeJunkie_StateChart_Example_Timer_State_PoweredOff : PowerButtonPressed

```