@startuml VendingMachine
state "VendingMachine State" as CodeJunkie_StateChart_Example_VendingMachine_State {
  state "SelectionEditable" as CodeJunkie_StateChart_Example_VendingMachine_SelectionEditable {
    state "Idle" as CodeJunkie_StateChart_Example_VendingMachine_Idle
    state "TransactionActive" as CodeJunkie_StateChart_Example_VendingMachine_TransactionActive {
      state "TransactionStarted" as CodeJunkie_StateChart_Example_VendingMachine_TransactionStarted
    }
  }
  state "Vending" as CodeJunkie_StateChart_Example_VendingMachine_Vending
}

CodeJunkie_StateChart_Example_VendingMachine_Idle --> CodeJunkie_StateChart_Example_VendingMachine_Idle : PaymentReceived
CodeJunkie_StateChart_Example_VendingMachine_SelectionEditable --> CodeJunkie_StateChart_Example_VendingMachine_SelectionEditable : SelectionEntered
CodeJunkie_StateChart_Example_VendingMachine_SelectionEditable --> CodeJunkie_StateChart_Example_VendingMachine_TransactionStarted : SelectionEntered
CodeJunkie_StateChart_Example_VendingMachine_TransactionActive --> CodeJunkie_StateChart_Example_VendingMachine_Idle : TransactionTimedOut
CodeJunkie_StateChart_Example_VendingMachine_TransactionActive --> CodeJunkie_StateChart_Example_VendingMachine_TransactionActive : PaymentReceived
CodeJunkie_StateChart_Example_VendingMachine_TransactionActive --> CodeJunkie_StateChart_Example_VendingMachine_Vending : PaymentReceived
CodeJunkie_StateChart_Example_VendingMachine_TransactionStarted --> CodeJunkie_StateChart_Example_VendingMachine_TransactionStarted : SelectionEntered
CodeJunkie_StateChart_Example_VendingMachine_Vending --> CodeJunkie_StateChart_Example_VendingMachine_Idle : VendingCompleted

CodeJunkie_StateChart_Example_VendingMachine_Idle : OnEnter → ClearTransactionTimeOutTimer
CodeJunkie_StateChart_Example_VendingMachine_Idle : OnPaymentReceived → MakeChange
CodeJunkie_StateChart_Example_VendingMachine_SelectionEditable : OnSelectionEntered → RestartTransactionTimeOutTimer
CodeJunkie_StateChart_Example_VendingMachine_TransactionActive : OnEnter → RestartTransactionTimeOutTimer
CodeJunkie_StateChart_Example_VendingMachine_TransactionActive : OnPaymentReceived → MakeChange, RestartTransactionTimeOutTimer, TransactionCompleted
CodeJunkie_StateChart_Example_VendingMachine_TransactionActive : OnTransactionTimedOut → MakeChange
CodeJunkie_StateChart_Example_VendingMachine_TransactionStarted : OnEnter → TransactionStarted
CodeJunkie_StateChart_Example_VendingMachine_TransactionStarted : OnSelectionEntered → RestartTransactionTimeOutTimer
CodeJunkie_StateChart_Example_VendingMachine_Vending : OnEnter → BeginVending

[*] --> CodeJunkie_StateChart_Example_VendingMachine_Idle
@enduml